[[hosts]]
name = "nihilicht-sagittarius"
arch = "x86_64-linux"
users = ["tsukuyomi"]

[[users]]
name = "tsukuyomi"
home = true
groups = ["wheel"]
desktop = "hyprland"
environment = "tsukuyomi"
programs = ["honkers-railway-launcher"]
